= oVirt Dashboard

== Introduction

This project contains http://www.ovirt.org/[oVirt]
http://www.ovirt.org/develop/release-management/features/ux/uiplugins/[UI plugin]
that gives overview of the virtualized environment and its specific objects.

This plugin is installed during oVirt Engine installation and upgraded via `engine-setup`.
This means no manual steps are required in order to install this plugin in production env.

== Setting up development environment

=== Prerequisites

Install https://nodejs.org/[Node.js] v6 (LTS). https://github.com/creationix/nvm[nvm]
can be used to manage multiple Node.js versions.

Run `node -v` to check the current Node.js version.

Build and configure oVirt Engine according to its
https://gerrit.ovirt.org/gitweb?p=ovirt-engine.git;a=blob_plain;f=README.adoc;hb=master[developer instructions].

=== Dashboard setup

* `yarn install` to install dependencies (this might take a while)
* `yarn test` to run tests (single run)
* `yarn run test:watch` for continuous testing (watch & rerun tests on change)
* `yarn run dev` for development build and watch & recompile files on change
* `yarn run build` for production build

=== Engine setup

Symlink plugin resources to `ui-plugins` directory as following:

  cd ${PREFIX}/share/ovirt-engine/ui-plugins/
  ln -s ${PLUGIN_HOME}/dist/dashboard.json dashboard.json
  ln -s ${PLUGIN_HOME}/dist/dashboard-resources dashboard-resources

=== Accessing plugin

Open WebAdmin in your browser, you should land on *Dashboard* main tab automatically:

  https://engine.example:8443/ovirt-engine/webadmin/WebAdmin.html

== Instructions for maintainers

=== Managing dependencies

Dependencies not related to production build (not needed for `yarn run build`)
should go into `devDependencies`. Try to keep as few `dependencies` as possible.

Whenever `dependencies` are changed:

* submit patch for https://gerrit.ovirt.org/#/q/project:releng-tools[releng-tools]:
** `specs/ovirt-engine-nodejs-modules/package.json` - reflect required dependencies
** `specs/ovirt-engine-nodejs-modules/ovirt-engine-nodejs-modules.spec.in` - bump `Version` and update `%changelog`
** `specs/ovirt-engine-nodejs-modules/CHANGES.adoc` - document changes made to `package.json`

=== Package versioning

* alpha and beta builds (pre-releases): `x.y.z-0.N` where version stays the same
* RC and GA builds (releases): `x.y.z-N` where version grows between releases

`version` in `package.json` is reflected into the RPM `x.y.z` version.

=== Release process

Only covers release builds (RC and GA).

==== Stable branches

To create new stable branch:

. create new branch via https://gerrit.ovirt.org/#/admin/projects/ovirt-engine-dashboard,branches[Gerrit]
. rebase on top of the newly created branch
. submit patch with following changes:
.. `automation/*.repos` - ensure proper oVirt repos (don't use `ovirt-master-snapshot`)

Then, update the master branch:

* submit patch with following changes:
** `package.json` - bump `version`
** `packaging/spec.in` - reset `Release` number to `0.1` and update `%changelog`

Finally, update Jenkins CI job config:

* submit patch for https://gerrit.ovirt.org/#/q/project:jenkins[jenkins]:
** `jobs/confs/projects/ovirt-engine-dashboard/ovirt-engine-dashboard_standard.yaml` - ensure that `version`
   contains the Engine version to corresponding Dashboard stable branch mapping

==== Releases

To perform new release:

. switch to appropriate stable branch
. submit patch that prepares the branch for release:
.. `package.json` - ensure proper `version` (e.g. bump `.z` component)
.. `packaging/spec.in` - ensure proper `Release` number and update `%changelog`
. pull changes from remote
. tag release-prep patch and push the tag to remote:
.. `git tag -a <tag-name>`
.. `git push origin <tag-name>`
. trigger Jenkins build on release-prep patch
. update oVirt release config in `releng-tools` repo

Tag name example: `ovirt-engine-dashboard-1.0.0-1`

=== Building RPM

To build RPM from an open patch, just post `ci please build` comment on Gerrit. See
https://www.ovirt.org/blog/2016/12/ci-please-build/[this blog post] for details on this CI feature.

Alternatively, RPM can be built locally using
http://ovirt-infra-docs.readthedocs.io/en/latest/CI/Build_and_test_standards.html#testing-the-scripts-locally[mock_runner].
